version: "3.9"

services:

  es:
    image: elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  db:
    image: postgres
    env_file:
      - ./insura/.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"
    env_file:
      - ./insura/.env

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./insura:/code
    ports:
      - "8000:8000"
    depends_on:
      - es
      - db
      - rabbit

  celery:
    build: .
    command: celery -A insura worker -l info
    volumes:
      - ./insura:/code
