# Generated by Django 3.2.10 on 2022-02-11 12:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Компания')),
                ('description', models.TextField(blank=True, verbose_name='Описание компании')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Продукт')),
                ('type', models.CharField(choices=[('Автострахование', 'Автострахование'), ('Недвижимость', 'Недвижимость'), ('Жизнь', 'Жизнь')], max_length=50, verbose_name='Тип')),
                ('rate', models.IntegerField(verbose_name='Ставка %')),
                ('period', models.CharField(choices=[('1 месяц', '1 месяц'), ('3 месяца', '3 месяца'), ('6 месяцев', '6 месяцев'), ('1 год', '1 год'), ('3 года', '3 года'), ('5 лет', '5 лет'), ('10 лет', '10 лет')], max_length=30, verbose_name='Период')),
                ('description', models.TextField(blank=True, verbose_name='Описание продукта')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.company', verbose_name='Компания')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('date_send', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Время отправки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product', verbose_name='Продукт')),
            ],
        ),
    ]
