# Generated by Django 3.2.10 on 2022-02-05 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='mail',
            new_name='email',
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание компании'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Продукт/Услуга'),
        ),
        migrations.AlterField(
            model_name='product',
            name='period',
            field=models.CharField(choices=[('1 месяц', '1 месяц'), ('3 месяца', '3 месяца'), ('6 месяцев', '6 месяцев'), ('1 год', '1 год'), ('3 года', '3 года'), ('5 лет', '5 лет'), ('10 лет', '10 лет')], max_length=30),
        ),
        migrations.AlterField(
            model_name='response',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
