# Generated by Django 3.2.10 on 2022-02-12 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(verbose_name='Описание компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание продукта'),
        ),
        migrations.AlterField(
            model_name='response',
            name='date_send',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время отправки'),
        ),
    ]
