# Generated by Django 3.2.10 on 2022-02-16 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20220212_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='response',
            name='date_send',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отправки'),
        ),
    ]
