# Generated by Django 3.2.10 on 2022-02-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='period',
            field=models.CharField(choices=[('1 месяц', '1 месяц'), ('3 месяца', '3 месяца'), ('6 месяцев', '6 месяцев'), ('1 год', '1 год'), ('3 года', '3 года'), ('5 лет', '5 лет'), ('10 лет', '10 лет')], max_length=30, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(verbose_name='Ставка %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Автострахование', 'Автострахование'), ('Недвижимость', 'Недвижимость'), ('Жизнь', 'Жизнь')], max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='response',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='response',
            name='name',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
    ]
